services:
  front-imc:
    image: ddb7/front-ddb:latest
    container_name: front-ddb
    ports:
      - 3001:80
    networks:
      - imc-network

networks:
  imc-network:
    name: imc-network
    external: true