load_module modules/ngx_otel_module.so;

worker_processes  auto;

events {}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    otel_exporter {
        endpoint http://ams-otel:4318/v1/traces;
        service_name nginx-frontend;
    }

    otel_tracer_provider {
        sampler_ratio 1.0;
    }

    server {
        listen 80;
        server_name _;


        location / {
            otel_trace;

            try_files $uri /index.html;
            root /usr/share/nginx/html;
            index index.html;
        }

        location /imc {
            proxy_pass http://ms-imc:8080/imc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
